import type { components } from "./schema"

type Schemas = components["schemas"]

export type Course = Schemas["Course"]
export type Student = Schemas["Student"]
export type RosterChange = Schemas["RosterChange"]
export type AssignmentInfo = Schemas["AssignmentInfo"]
export type VersionSummary = Schemas["VersionSummary"]
export type Problem = Schemas["Problem"]
export type TemplatePage = Schemas["TemplatePage"]
export type Box = Schemas["Box"]
export type Job = Schemas["Job"]
export type ScanPage = Schemas["ScanPage"]
export type SubmissionInfo = Schemas["SubmissionInfo"]
export type NameRow = Schemas["NameRow"]
export type Candidate = Schemas["Candidate"]
export type QuestionInfo = Schemas["QuestionInfo"]
export type RubricItem = Schemas["RubricItem"]
export type ErrorBody = Schemas["ErrorBody"]
