/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesCourseIndexRouteImport } from './routes/courses/$course/index'
import { Route as CoursesCourseAssignmentRouteImport } from './routes/courses/$course/$assignment'
import { Route as CoursesCourseNewRouteImport } from './routes/courses/$course/new'
import { Route as CoursesCourseAssignmentIndexRouteImport } from './routes/courses/$course/$assignment/index'
import { Route as CoursesCourseAssignmentOutlineRouteImport } from './routes/courses/$course/$assignment/outline'
import { Route as CoursesCourseAssignmentTemplatesRouteImport } from './routes/courses/$course/$assignment/templates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIndexRoute = CoursesCourseIndexRouteImport.update({
  id: '/courses/$course/',
  path: '/courses/$course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseAssignmentRoute = CoursesCourseAssignmentRouteImport.update({
  id: '/courses/$course/$assignment',
  path: '/courses/$course/$assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseNewRoute = CoursesCourseNewRouteImport.update({
  id: '/courses/$course/new',
  path: '/courses/$course/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseAssignmentIndexRoute =
  CoursesCourseAssignmentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoursesCourseAssignmentRoute,
  } as any)
const CoursesCourseAssignmentOutlineRoute =
  CoursesCourseAssignmentOutlineRouteImport.update({
    id: '/outline',
    path: '/outline',
    getParentRoute: () => CoursesCourseAssignmentRoute,
  } as any)
const CoursesCourseAssignmentTemplatesRoute =
  CoursesCourseAssignmentTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => CoursesCourseAssignmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses/$course/$assignment': typeof CoursesCourseAssignmentRouteWithChildren
  '/courses/$course/new': typeof CoursesCourseNewRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/courses/$course/$assignment/outline': typeof CoursesCourseAssignmentOutlineRoute
  '/courses/$course/$assignment/templates': typeof CoursesCourseAssignmentTemplatesRoute
  '/courses/$course/$assignment/': typeof CoursesCourseAssignmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses/$course/new': typeof CoursesCourseNewRoute
  '/courses/$course': typeof CoursesCourseIndexRoute
  '/courses/$course/$assignment/outline': typeof CoursesCourseAssignmentOutlineRoute
  '/courses/$course/$assignment/templates': typeof CoursesCourseAssignmentTemplatesRoute
  '/courses/$course/$assignment': typeof CoursesCourseAssignmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses/$course/$assignment': typeof CoursesCourseAssignmentRouteWithChildren
  '/courses/$course/new': typeof CoursesCourseNewRoute
  '/courses/$course/': typeof CoursesCourseIndexRoute
  '/courses/$course/$assignment/outline': typeof CoursesCourseAssignmentOutlineRoute
  '/courses/$course/$assignment/templates': typeof CoursesCourseAssignmentTemplatesRoute
  '/courses/$course/$assignment/': typeof CoursesCourseAssignmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses/$course/$assignment'
    | '/courses/$course/new'
    | '/courses/$course/'
    | '/courses/$course/$assignment/outline'
    | '/courses/$course/$assignment/templates'
    | '/courses/$course/$assignment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses/$course/new'
    | '/courses/$course'
    | '/courses/$course/$assignment/outline'
    | '/courses/$course/$assignment/templates'
    | '/courses/$course/$assignment'
  id:
    | '__root__'
    | '/'
    | '/courses/$course/$assignment'
    | '/courses/$course/new'
    | '/courses/$course/'
    | '/courses/$course/$assignment/outline'
    | '/courses/$course/$assignment/templates'
    | '/courses/$course/$assignment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesCourseAssignmentRoute: typeof CoursesCourseAssignmentRouteWithChildren
  CoursesCourseNewRoute: typeof CoursesCourseNewRoute
  CoursesCourseIndexRoute: typeof CoursesCourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/': {
      id: '/courses/$course/'
      path: '/courses/$course'
      fullPath: '/courses/$course/'
      preLoaderRoute: typeof CoursesCourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$assignment': {
      id: '/courses/$course/$assignment'
      path: '/courses/$course/$assignment'
      fullPath: '/courses/$course/$assignment'
      preLoaderRoute: typeof CoursesCourseAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/new': {
      id: '/courses/$course/new'
      path: '/courses/$course/new'
      fullPath: '/courses/$course/new'
      preLoaderRoute: typeof CoursesCourseNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$course/$assignment/': {
      id: '/courses/$course/$assignment/'
      path: '/'
      fullPath: '/courses/$course/$assignment/'
      preLoaderRoute: typeof CoursesCourseAssignmentIndexRouteImport
      parentRoute: typeof CoursesCourseAssignmentRoute
    }
    '/courses/$course/$assignment/outline': {
      id: '/courses/$course/$assignment/outline'
      path: '/outline'
      fullPath: '/courses/$course/$assignment/outline'
      preLoaderRoute: typeof CoursesCourseAssignmentOutlineRouteImport
      parentRoute: typeof CoursesCourseAssignmentRoute
    }
    '/courses/$course/$assignment/templates': {
      id: '/courses/$course/$assignment/templates'
      path: '/templates'
      fullPath: '/courses/$course/$assignment/templates'
      preLoaderRoute: typeof CoursesCourseAssignmentTemplatesRouteImport
      parentRoute: typeof CoursesCourseAssignmentRoute
    }
  }
}

interface CoursesCourseAssignmentRouteChildren {
  CoursesCourseAssignmentOutlineRoute: typeof CoursesCourseAssignmentOutlineRoute
  CoursesCourseAssignmentTemplatesRoute: typeof CoursesCourseAssignmentTemplatesRoute
  CoursesCourseAssignmentIndexRoute: typeof CoursesCourseAssignmentIndexRoute
}

const CoursesCourseAssignmentRouteChildren: CoursesCourseAssignmentRouteChildren =
  {
    CoursesCourseAssignmentOutlineRoute: CoursesCourseAssignmentOutlineRoute,
    CoursesCourseAssignmentTemplatesRoute:
      CoursesCourseAssignmentTemplatesRoute,
    CoursesCourseAssignmentIndexRoute: CoursesCourseAssignmentIndexRoute,
  }

const CoursesCourseAssignmentRouteWithChildren =
  CoursesCourseAssignmentRoute._addFileChildren(
    CoursesCourseAssignmentRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesCourseAssignmentRoute: CoursesCourseAssignmentRouteWithChildren,
  CoursesCourseNewRoute: CoursesCourseNewRoute,
  CoursesCourseIndexRoute: CoursesCourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
